### ISSUE TITLE
Dialogs de cierre de sesion

### ISSUE THREAD

**Issue by Camila-C** [IngSoftIII2016/saga-angular-client#14]
Cuando hay una sesion abierta y se hace clic en el boton de inicio de sesion, se deberia consultar si desea cerrar sesion e iniciar con una cuenta diferente. Lo mismo podria suceder con el boton de cerrar sesion.

**Comment by jpaveggio** [comment]
Agregar tooltip para clarificar funcion de los iconos, login, logout, editar perfil
