### ISSUE TITLE
Alta de aulas

### ISSUE THREAD

**Issue by Camila-C** [IngSoftIII2016/saga-angular-client#20]
Al intentar dar de alta un aula que no pasa la verirficacion, no se puede hacer un alta nueva despues si no se ingresan datos completamente diferentes a los del alta con error, incluso despues de recargar la pagina o cerrar sesion. Consola muestra error 400.

**Comment by JavierJV** [comment]
cami, yo modifique alta de aulas por otra cosa (podias agregar aulas sin nombre) ya lo modifique, podrias volver a probar??
