### ISSUE TITLE
alta de evento

### ISSUE THREAD

**Issue by Camila-C** [IngSoftIII2016/saga-angular-client#34]
- alta de evento admite fechas y  horarios anteriores a la hora actual
- el dialogo de creacion no marca el motivo como campo requerido
- el dialogo de creacion dice "fecha fin" en lugar de "hora fin"

**Comment by fdifabio** [comment]
El item dos y tres ya estaban hechos. Ahora solo admite la fecha de hoy o mayor. En cuanto a horas no pude configurarlo.
![image](https://cloud.githubusercontent.com/assets/16326497/22720863/506749f6-ed8c-11e6-8fc8-bdbc0d57ea92.png)
