### ISSUE TITLE
Administrador Academico > inicio

### ISSUE THREAD

**Issue by Camila-C** [IngSoftIII2016/saga-angular-client#36]
La unica forma de regresar al inicio desde cualquier vista de Admin. Ac. es haciendo clic en la parte del logo que dice "universidad nacional de rio negro", el logo entero no es un link. (Si no fuera tan chiquito no habria problema)

**Comment by fdifabio** [comment]
Pero haciendo click sobre el menu, donde dice "grilla" tmb se vuelve al inicio.

**Comment by fdifabio** [comment]
Ahí entendí, ya lo solucione
